{
 "title": "Credit Card Fraud Analysis",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Normal  Count",
   "type": "singlestat",
   "description": "Total number of Normal transactions",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "credit_total{fraud=\"NORMAL\"}"
    }
   ]
  },
  {
   "title": "Fraud Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(credit_total) by(fraud)))",
     "legendFormat": "{{fraud}}"
    }
   ]
  },
  {
   "title": "Fraud  Rate Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(credit_total{fraud=\"FRAUD\"}[60s])",
     "legendFormat": "FRAUD"
    }
   ]
  },
  {
   "title": "Fraud Count",
   "type": "singlestat",
   "description": "Total number of Fraud transactions",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "credit_total{fraud=\"FRAUD\"}"
    }
   ]
  },
  { "title": "Fraud Alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 6, "x": 0, "y": 8 } },
  {
   "title": "Fraud / Normal Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(credit_total{fraud=\"NORMAL\"}[60s])",
     "legendFormat": "{{fraud}}"
    },
    {
     "expr": "rate(credit_total{fraud=\"FRAUD\"}[60s])",
     "legendFormat": "{{fraud}}"
    }
   ]
  }
 ]
}